CREATE TYPE dish AS ENUM
    ('poisson', 'poulet au curry', 'poulet', 'canard', 'riz', 'boeuf', 'legumes');


CREATE TABLE IF NOT EXISTS client
(
    firstname character varying(30) COLLATE pg_catalog."default" NOT NULL,
    lastname character varying(30) COLLATE pg_catalog."default" NOT NULL,
    telephone character varying(20) COLLATE pg_catalog."default",
    mail character varying(100) COLLATE pg_catalog."default" NOT NULL,
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 104 INCREMENT BY 1),
    CONSTRAINT client_firstname_lastname_key UNIQUE (firstname)
    INCLUDE(lastname),
    CONSTRAINT client_mail_key UNIQUE (mail),
    CONSTRAINT client_telephone_key UNIQUE (telephone),
    CONSTRAINT "uniqueUser" UNIQUE (id),
    CONSTRAINT id_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS command
(
    price integer,
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 204 INCREMENT BY 1),
    clientid integer,
    date date DEFAULT CURRENT_DATE,
    dishes dish NOT NULL,
    CONSTRAINT command_id_key UNIQUE (id),
    CONSTRAINT idc_pkey PRIMARY KEY (id)
    );

-- Données pour la table client
INSERT INTO client (firstname, lastname, telephone, mail) VALUES
                                                              ('Jean', 'Dupont', '0123456789', 'jean.dupont@example.com'),
                                                              ('Marie', 'Dubois', '0234567890', 'marie.dubois@example.com'),
                                                              ('Pierre', 'Martin', '0345678901', 'pierre.martin@example.com'),
                                                              ('Sophie', 'Thomas', '0456789012', 'sophie.thomas@example.com');

-- Données pour la table command
INSERT INTO command (price, clientid, date, dishes) VALUES
                                                        (25, 101, '2024-02-22', 'poulet'),
                                                        (30, 102, '2024-02-21', 'boeuf'),
                                                        (20, 103, '2024-02-20', 'riz'),
                                                        (35, 104, '2024-02-19', 'poisson');