version: '3.8'

services:
  psql-db:
    image: 'postgres:16.2-alpine3.19'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vasco
      - POSTGRES_DB=foodliao
    ports:
      - '5434:5432'

  app:
    build: ./app
    container_name: app
    depends_on:
      - psql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/foodliao
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=vasco
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8081:8080'


